version: 2.1

jobs:
  Test-API:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run API tests
          command: |
            cd API_Tests
            npm install
            npm test
