version: 2.1
jobs:
  Test-API:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run API tests
          command: |
            cd API_Tests
            npm install
            npm run dev &
            npm test
  Test-UI:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run UI tests
          command: |
            cd UI_Tests
            npm install
            npx nightwatch

workflows:
  Test-My-App:
    jobs:
      - Test-UI
      - Test-API:
        requires:
          - Test-UI
