version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  Test-API:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages
      # - run:
      #     name: Run UI tests
      #     command: |
      #       cd UI_Tests
      #       npm install
      #       npm test
      - run:
          name: Run API tests
          command: |
            cd API_Tests
            npm install
            npm test
